version: '2'

networks:
  dev-network:
    driver: bridge
services:
  database:
    image: mysql:5.7
    networks:
      - dev-network
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - simple-mysql:/var/lib/mysql
  keycloak:
    networks:
      - dev-network
    image: jboss/keycloak:7.0.0
    restart: on-failure

    environment:
      - KEYCLOAK_USER=keyadmin
      - KEYCLOAK_PASSWORD=k3radmin
      - DB_VENDOR=mysql
      - DB_USER=keycloak
      - DB_PASSWORD=k34cloak
      - DB_ADDR=database
      - DB_PORT=3306
      - DB_DATABASE=keycloakdb
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8081:8080"
    depends_on:
      - database
volumes:
  simple-mysql:
    external: true